language: go

go:
  - 1.5

before_install:
  - sudo add-apt-repository -y ppa:kalakris/cmake
  - sudo add-apt-repository -y ppa:team-xbmc/ppa
  - sudo apt-get update -qq

install:
  - sudo apt-get install cmake portaudio19-dev
  - go get github.com/veandco/go-sdl2/sdl
  - go get github.com/gordonklaus/portaudio
  - go get github.com/Sirupsen/logrus
  - go get github.com/stretchr/testify/assert
  - go get github.com/stretchr/testify/mock
  - go get github.com/youpy/go-wav

